# Naming: patheya-express/<environment>/<purpose> — a path-style prefix scoped by environment,
# so the IRSA policy for External Secrets Operator (modules/eks-addons/external-secrets.tf) can
# grant secretsmanager:GetSecretValue against "patheya-express/<environment>/*" and nothing
# outside it, matching platform-standards.md Section 4's naming table row for Secrets Manager
# would follow if it had one, and least-privilege (Section 1, principle 8).

resource "random_password" "redis_auth_token" {
  # ElastiCache AUTH token constraints: 16-128 printable ASCII characters, excluding
  # @ " / and space (the four characters the Redis AUTH protocol and ElastiCache's own token
  # validation both reject) — special_chars intentionally narrowed below rather than disabled
  # entirely, since a token with zero special characters is weaker for no protocol-compliance
  # reason.
  length           = 64
  special          = true
  override_special = "!&#$^<>-"
}

resource "aws_secretsmanager_secret" "redis_auth_token" {
  name        = "patheya-express/${var.environment}/redis-auth-token"
  description = "ElastiCache Redis AUTH token — generated by Terraform, rotated manually (rotating requires a coordinated app-side reconnect, same rationale as JWT secrets in platform-standards.md Section 13)."
  kms_key_id  = var.kms_key_arn

  tags = merge(var.tags, { Application = "secrets-manager", Purpose = "redis-auth-token" })
}

resource "aws_secretsmanager_secret_version" "redis_auth_token" {
  secret_id     = aws_secretsmanager_secret.redis_auth_token.id
  secret_string = random_password.redis_auth_token.result
}

# Empty containers for external SaaS credentials this module has no legitimate way to generate —
# see variables.tf's description. A human populates aws_secretsmanager_secret_version out-of-band
# (docs/secrets-guide.md documents the exact `aws secretsmanager put-secret-value` command).
resource "aws_secretsmanager_secret" "external_credentials" {
  for_each = toset(var.external_credential_secrets)

  name        = "patheya-express/${var.environment}/${each.value}"
  description = "External credential — value populated out-of-band by a human, never by Terraform. See docs/secrets-guide.md."
  kms_key_id  = var.kms_key_arn

  tags = merge(var.tags, { Application = "secrets-manager", Purpose = each.value })
}
