# Grafana's admin password — Terraform-generated (a platform-invented credential, not an
# external SaaS one), exactly the same pattern modules/secrets-manager already established for
# the Redis AUTH token. Never a literal value in any environment's tfvars, never hardcoded in the
# Helm values template.

resource "random_password" "grafana_admin" {
  length  = 32
  special = true
  # Grafana's admin password has no character-set restriction the way ElastiCache's AUTH token
  # does — no override_special needed.
}

resource "aws_secretsmanager_secret" "grafana_admin" {
  name        = "${var.secrets_manager_path_prefix}/grafana-admin"
  description = "Grafana admin credentials — generated by Terraform, synced into the cluster by External Secrets Operator (Phase 4)."
  kms_key_id  = var.kms_key_arn

  tags = merge(var.tags, { Application = "observability", Purpose = "grafana-admin-credential" })
}

resource "aws_secretsmanager_secret_version" "grafana_admin" {
  secret_id = aws_secretsmanager_secret.grafana_admin.id
  secret_string = jsonencode({
    username = "admin"
    password = random_password.grafana_admin.result
  })
}

# Synced by the SAME ClusterSecretStore Phase 4 already installed (modules/eks-addons/
# external-secrets.tf) — this module doesn't install its own second External Secrets Operator or
# a second ClusterSecretStore; it just adds one more ExternalSecret referencing the existing one.
resource "kubernetes_manifest" "grafana_admin_external_secret" {
  manifest = {
    apiVersion = "external-secrets.io/v1beta1"
    kind       = "ExternalSecret"
    metadata = {
      name      = "grafana-admin-credentials"
      namespace = "monitoring"
    }
    spec = {
      refreshInterval = "1h"
      secretStoreRef = {
        name = "aws-secrets-manager"
        kind = "ClusterSecretStore"
      }
      target = {
        name           = "grafana-admin-credentials"
        creationPolicy = "Owner"
      }
      dataFrom = [
        {
          extract = {
            key = aws_secretsmanager_secret.grafana_admin.arn
          }
        }
      ]
    }
  }
}
